package com.khatabook.app.data.repository

import android.content.Context
import android.content.SharedPreferences
import com.khatabook.app.data.dao.TransactionDao
import com.khatabook.app.data.entity.InvoiceItemEntity
import com.khatabook.app.data.entity.TransactionEntity
import com.khatabook.app.util.Constants
import com.khatabook.app.util.PkDateTime
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.Flow
import javax.inject.Inject
import javax.inject.Singleton

/**
 * ═══════════════════════════════════════════════════════════════════
 * INVOICE REPOSITORY — Assemble invoice data from multiple sources
 * ═══════════════════════════════════════════════════════════════════
 *
 * Combines:
 *   - TransactionEntity (customer, amount, date)
 *   - InvoiceItemEntity list (line items)
 *   - Shop name from SharedPreferences
 */
@Singleton
class InvoiceRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val transactionDao: TransactionDao,
    private val invoiceItemRepository: InvoiceItemRepository
) {
    private val prefs: SharedPreferences =
        context.getSharedPreferences(Constants.PREFS_NAME, Context.MODE_PRIVATE)

    /** Shop name saved during onboarding / settings */
    fun getShopName(): String {
        return prefs.getString(Constants.KEY_SHOP_NAME, Constants.APP_NAME)
            ?: Constants.APP_NAME
    }

    /** Get a transaction by ID (reactive) */
    fun getTransactionById(id: Long): Flow<TransactionEntity?> {
        return transactionDao.getTransactionById(id)
    }

    /** Get invoice line items for a transaction (reactive) */
    fun getInvoiceItems(transactionId: Long): Flow<List<InvoiceItemEntity>> {
        return invoiceItemRepository.getItemsForTransaction(transactionId)
    }

    /** Get invoice line items (one-shot) */
    suspend fun getInvoiceItemsOnce(transactionId: Long): List<InvoiceItemEntity> {
        return invoiceItemRepository.getItemsForTransactionOnce(transactionId)
    }

    /**
     * Build plain-text invoice string for WhatsApp sharing.
     * No items → simple amount-based bill.
     * With items → itemized bill.
     */
    fun buildInvoiceText(
        transaction: TransactionEntity,
        items: List<InvoiceItemEntity>,
        shopName: String = getShopName()
    ): String {
        val dateStr = PkDateTime.formatDisplayDate(transaction.date)

        return buildString {
            appendLine("═══════════════════════════════")
            appendLine("         KHATA ONE")
            appendLine("           INVOICE")
            appendLine("═══════════════════════════════")
            appendLine()
            appendLine("Shop: $shopName")
            appendLine("Customer: ${transaction.customerName}")
            appendLine("Date: $dateStr")
            appendLine("Invoice #: INV-${transaction.id}")
            appendLine()

            if (items.isNotEmpty()) {
                // Itemized bill
                appendLine("───────────────────────────────")
                appendLine("Item            Qty   Price    Total")
                appendLine("───────────────────────────────")
                items.forEach { item ->
                    val name = item.productName.take(14).padEnd(15)
                    val qty = "${item.quantity} ${item.unit}".take(5).padStart(6)
                    val price = "Rs ${String.format("%,.0f", item.unitPrice)}".padStart(9)
                    val total = "Rs ${String.format("%,.0f", item.totalPrice)}".padStart(10)
                    appendLine("$name $qty $price $total")
                }
                appendLine("───────────────────────────────")
                val itemsTotal = items.sumOf { it.totalPrice }
                appendLine("Subtotal: Rs ${String.format("%,.0f", itemsTotal)}")
                if (transaction.amount != itemsTotal) {
                    appendLine("Adjustment: Rs ${String.format("%,.0f", transaction.amount - itemsTotal)}")
                }
            }

            appendLine()
            appendLine("Total Amount: Rs ${String.format("%,.0f", transaction.amount)}")
            appendLine()
            appendLine("═══════════════════════════════")
            appendLine("Thank you for your business!")
            appendLine("Generated by Khata One")
            appendLine("═══════════════════════════════")
        }
    }
}
